<?php

/**
 * Implements hook_menu().
 */
function sse_admintype_menu() {
  $types = node_type_get_types();
  foreach ($types as $type) {
    $items['admin/content/'.$type->type] = [
      'title' => '管理'.$type->name,
      'page callback' => 'drupal_goto',
      'page arguments' => [
        'admin/content',
        [
          'query' => [
            'type' => $type->type
          ]
        ]
      ],
      'menu name' => 'management',
      'access callback' => 'node_access',
      'access arguments' => array('create', $type->type),
      'weight' => 50
    ];
  };
  return $items;
}
